# Generated by Django 3.0.6 on 2020-05-15 19:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id',
                 models.UUIDField(default=uuid.uuid4,
                                  editable=False,
                                  primary_key=True,
                                  serialize=False)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by',
                 models.CharField(blank=True, max_length=200, null=True)),
                ('updated_by',
                 models.CharField(blank=True, max_length=200, null=True)),
                ('image_type',
                 models.CharField(choices=[(0, 'Sample Image'),
                                           (1, "User's Image"),
                                           (2, "Service's Image")],
                                  default=0,
                                  max_length=30,
                                  verbose_name='Image Type')),
                ('is_public',
                 models.BooleanField(default=False,
                                     verbose_name='Public Image')),
                ('image_url',
                 models.CharField(max_length=200, verbose_name='Image url')),
                ('image_public_id',
                 models.CharField(max_length=200, verbose_name='Image id')),
            ],
            options={
                'verbose_name_plural': 'Images',
                'db_table': 'images',
            },
        ),
    ]
