# Generated by Django 3.0.7 on 2020-06-28 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studio_session', '0001_initial'),
        ('image', '0002_image_is_hero_bg'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='studio_session_image',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='studio_session_image',
                to='studio_session.StudioSession'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_type',
            field=models.CharField(choices=[('0', 'Sample Image'),
                                            ('1', "User's Image"),
                                            ('2', "Service's Image")],
                                   default='0',
                                   max_length=30,
                                   verbose_name='Image Type'),
        ),
    ]
