# Generated by Django 3.0.7 on 2020-06-28 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudioSession',
            fields=[
                ('id',
                 models.UUIDField(default=uuid.uuid4,
                                  editable=False,
                                  primary_key=True,
                                  serialize=False)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by',
                 models.CharField(blank=True, max_length=200, null=True)),
                ('updated_by',
                 models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(max_length=200,
                                          verbose_name='Name ')),
                ('description',
                 models.TextField(max_length=400,
                                  verbose_name='Studio Session description')),
            ],
            options={
                'verbose_name_plural': 'Studio Sessions',
                'db_table': 'st_sessions',
            },
        ),
        migrations.CreateModel(
            name='StudioSessionCoordinator',
            fields=[
                ('id',
                 models.UUIDField(default=uuid.uuid4,
                                  editable=False,
                                  primary_key=True,
                                  serialize=False)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by',
                 models.CharField(blank=True, max_length=200, null=True)),
                ('updated_by',
                 models.CharField(blank=True, max_length=200, null=True)),
                ('start_of_day',
                 models.TimeField(verbose_name='Start time for the day')),
                ('end_of_day',
                 models.TimeField(verbose_name='End time for the day')),
                ('break_start_time',
                 models.TimeField(verbose_name='Daily break time')),
                ('break_duration',
                 models.IntegerField(default=60,
                                     verbose_name='Daily Break duration')),
                ('is_available',
                 models.BooleanField(
                     default=True, verbose_name="Coordinator's availability")),
                ('user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='studio_session_coordinator',
                                   to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Studio Session Coordinator',
                'db_table': 'st_session_coordinators',
            },
        ),
        migrations.CreateModel(
            name='StudioSessionType',
            fields=[
                ('id',
                 models.UUIDField(default=uuid.uuid4,
                                  editable=False,
                                  primary_key=True,
                                  serialize=False)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by',
                 models.CharField(blank=True, max_length=200, null=True)),
                ('updated_by',
                 models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(max_length=200,
                                          verbose_name='Name ')),
                ('price', models.FloatField(default=0.0,
                                            verbose_name='Price ')),
                ('max_duration',
                 models.IntegerField(default=30,
                                     verbose_name='Maximum duration')),
                ('studio_sessions',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.DO_NOTHING,
                     related_name='studio_session_type',
                     to='studio_session.StudioSession')),
            ],
            options={
                'verbose_name_plural': 'Studio Session Type',
                'db_table': 'st_session_types',
            },
        ),
        migrations.CreateModel(
            name='StudioSessionReservation',
            fields=[
                ('id',
                 models.UUIDField(default=uuid.uuid4,
                                  editable=False,
                                  primary_key=True,
                                  serialize=False)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by',
                 models.CharField(blank=True, max_length=200, null=True)),
                ('updated_by',
                 models.CharField(blank=True, max_length=200, null=True)),
                ('status',
                 models.CharField(choices=[
                     ('0', 'Pending'), ('1', 'Confirmed'), ('2', 'Arrived'),
                     ('3', 'Cancelled'), ('4', 'Done')
                 ],
                                  default='0',
                                  max_length=30,
                                  verbose_name='Reservation Status')),
                ('reservation_datetime',
                 models.DateTimeField(verbose_name='Reservation datetime')),
                ('duration',
                 models.IntegerField(default=30,
                                     verbose_name='Session duration')),
                ('coordinator',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='assigned_reservations',
                     to='studio_session.StudioSessionCoordinator')),
                ('session',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='session',
                                   to='studio_session.StudioSession')),
                ('user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='studio_sessions',
                                   to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Studio Session Reservation',
                'db_table': 'st_session_reservations',
            },
        ),
    ]
