# Generated by Django 3.0.7 on 2020-06-28 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio_session', '0002_auto_20200628_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studiosessiontype',
            old_name='studio_sessions',
            new_name='studio_session',
        ),
    ]
