# Generated by Django 3.0.6 on 2020-05-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heroimage',
            old_name='hero_image_url',
            new_name='hero_image',
        ),
        migrations.RenameField(
            model_name='portfolioimage',
            old_name='portfolio_image_url',
            new_name='portfolio_image',
        ),
        migrations.AlterField(
            model_name='portfolioimage',
            name='portfolio_description',
            field=models.CharField(blank=True,
                                   max_length=20,
                                   null=True,
                                   verbose_name='Portfolio Desc.'),
        ),
    ]
